# Generated by Django 4.1.6 on 2023-02-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_by')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')], default=1)),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='joined_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('jwt_issue_dt', models.CharField(max_length=100, null=True)),
                ('invalid_attempt', models.IntegerField(default=0)),
                ('holding_datetime', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'User Authentication',
                'get_latest_by': 'key',
                'unique_together': {('username', 'user_type')},
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('factor_auth', models.CharField(max_length=10)),
                ('session_in_activity', models.CharField(max_length=200)),
                ('simultaneous_login', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Users Group',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=100, null=True, verbose_name='dob')),
                ('os', models.BigIntegerField(default=0, null=True)),
                ('mac_address', models.TextField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.userauthentication')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.usergroup')),
            ],
            options={
                'verbose_name_plural': 'User',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('dob', models.CharField(max_length=100, verbose_name='dob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.role')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.userauthentication')),
            ],
            options={
                'verbose_name_plural': 'Admin',
            },
        ),
    ]
