# Generated by Django 4.1.6 on 2023-02-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0003_antivirusnegativepathmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSuperClass',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'FileClassification Super Class',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='AppClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('class_super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'App FileClassification',
                'get_latest_by': 'key',
            },
        ),
    ]
