# Generated by Django 4.1.6 on 2023-02-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0005_appcontrolpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClassificationGroup',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Base FileClassification Group',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='AppControlPolicyData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2)),
                ('app_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_class_grp', to='epsapp.baseclassificationgroup')),
                ('app_control_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.appcontrolpolicy')),
                ('schedule_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_class_grp', to='epsapp.baseclassificationgroup')),
            ],
            options={
                'verbose_name_plural': 'App Control Policy Data',
            },
        ),
        migrations.CreateModel(
            name='AppClassData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('column', models.CharField(max_length=20, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('app_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.appclassification')),
            ],
            options={
                'verbose_name_plural': 'App FileClassification Data',
            },
        ),
    ]
