# Generated by Django 4.1.6 on 2023-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0007_alter_baseclassificationgroup_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclassification',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appcontrolpolicy',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
