# Generated by Django 4.1.6 on 2023-02-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0008_alter_appclassification_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFileAccessDlp',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'App File Access Dlp',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='AppFileAccessDlpData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2)),
                ('app_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_class_group_afa', to='epsapp.baseclassificationgroup')),
                ('app_file_access_dlp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.appfileaccessdlp')),
                ('file_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_class_group_afa', to='epsapp.baseclassificationgroup')),
                ('schedule_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_class_group_afa', to='epsapp.baseclassificationgroup')),
            ],
            options={
                'verbose_name_plural': 'App File Access Dlp Data',
            },
        ),
    ]
