# Generated by Django 4.1.6 on 2023-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0009_appfileaccessdlp_appfileaccessdlpdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclassificationgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
