# Generated by Django 4.1.6 on 2023-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0010_alter_baseclassificationgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, null=True, unique=True)),
                ('version_allowed', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'App Version',
                'get_latest_by': 'key',
            },
        ),
    ]
