# Generated by Django 4.1.6 on 2023-02-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0011_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTrails',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('user_login', models.DateTimeField(null=True)),
                ('user_logout', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=500, null=True)),
                ('user_ip', models.CharField(max_length=100, null=True)),
                ('user_os', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.userauthentication')),
            ],
            options={
                'verbose_name_plural': 'Auth Trails',
                'get_latest_by': 'key',
            },
        ),
    ]
