# Generated by Django 4.1.6 on 2023-02-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0012_authtrails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrails',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField()),
                ('action', models.CharField(max_length=255, null=True)),
                ('auth_trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.authtrails')),
            ],
            options={
                'verbose_name_plural': 'Audit Trails',
            },
        ),
    ]
