# Generated by Django 4.1.6 on 2023-02-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0013_audittrails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationGroupMapping',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.IntegerField(default=1)),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epsapp.baseclassificationgroup')),
                ('class_super', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
            ],
        ),
    ]
