# Generated by Django 4.1.6 on 2023-02-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0015_clipboarddlp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipboardDlpData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(default='allow', max_length=10)),
                ('clipboard_dlp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.clipboarddlp')),
                ('from_app_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_app_class_clp', to='epsapp.baseclassificationgroup')),
                ('schedule_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_class_clp', to='epsapp.baseclassificationgroup')),
                ('to_app_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_app_class_clp', to='epsapp.baseclassificationgroup')),
            ],
            options={
                'verbose_name_plural': 'Clipboard Dlp Data',
            },
        ),
    ]
