# Generated by Django 4.1.6 on 2023-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0016_clipboarddlpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('relation_of_data', models.CharField(max_length=5, null=True)),
                ('keyword_regex', models.CharField(max_length=150)),
                ('validation_type', models.CharField(max_length=15)),
                ('old_name', models.CharField(max_length=150, null=True)),
                ('validation_value', models.CharField(max_length=150, null=True)),
                ('no_of_matches', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'File Data',
                'get_latest_by': 'key',
            },
        ),
    ]
