# Generated by Django 4.1.6 on 2023-02-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0017_contentclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('device_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('device_name_regex', models.CharField(max_length=100, null=True)),
                ('vid', models.CharField(default=None, max_length=50, null=True)),
                ('pid', models.CharField(default=None, max_length=50, null=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('brand', models.CharField(default=None, max_length=25)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('class_super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Device FileClassification',
            },
        ),
    ]
