# Generated by Django 4.1.6 on 2023-02-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0018_deviceclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControlPolicy',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('usb_storage_device', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('cd_dvd', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('portable', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('wifi', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('bluetooth', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('webcam', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('serial_port', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('usb_port', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('local_printer', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('network_share', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('card_reader', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('unknown_device', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
                ('schedule_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.baseclassificationgroup')),
            ],
            options={
                'verbose_name_plural': 'DeviceControlPolicy',
            },
        ),
        migrations.CreateModel(
            name='DeviceException',
            fields=[
                ('types', models.IntegerField()),
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('action', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
                ('device_control_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.devicecontrolpolicy')),
            ],
            options={
                'verbose_name_plural': 'Device Exception',
                'get_latest_by': 'key',
            },
        ),
    ]
