# Generated by Django 4.1.6 on 2023-02-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0019_devicecontrolpolicy_deviceexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('class_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Web Classification',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=200)),
                ('web_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.webclassification')),
            ],
            options={
                'verbose_name_plural': 'Domain',
            },
        ),
    ]
