# Generated by Django 4.1.6 on 2023-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0020_webclassification_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTable',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('self_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('id_grand_parent', models.IntegerField()),
                ('id_parent', models.IntegerField()),
                ('is_hide', models.IntegerField()),
                ('position', models.IntegerField()),
                ('possible_permission', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Features Table',
                'get_latest_by': 'key',
            },
        ),
    ]
