# Generated by Django 4.1.6 on 2023-02-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0021_featuretable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('file_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('file_title', models.CharField(max_length=200, null=True)),
                ('file_desc', models.CharField(max_length=500, null=True)),
                ('file_ext', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=150, null=True)),
                ('program', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=150, null=True)),
                ('content_created', models.CharField(max_length=200, null=True)),
                ('date_last_saved', models.DateField(null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('owner', models.CharField(max_length=150, null=True)),
                ('folder_path', models.CharField(max_length=200, null=True)),
                ('custom', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
                ('class_super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.classificationsuperclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'File Classification',
                'get_latest_by': 'key',
            },
        ),
    ]
