# Generated by Django 4.1.6 on 2023-02-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0023_keystable_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPrinterDlp',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Local Printer Dlp',
                'get_latest_by': 'key',
            },
        ),
    ]
