# Generated by Django 4.1.6 on 2023-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0026_networkdlp_localprinterdlpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsTable',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Os Table',
                'get_latest_by': 'key',
            },
        ),
    ]
