# Generated by Django 4.1.6 on 2023-02-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0028_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAndAction',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.featuretable')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.role')),
            ],
        ),
    ]
