# Generated by Django 4.1.6 on 2023-02-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0030_rules_scheduleclassification_screenshotdlp_webdlp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('config_fetch_timeout', models.IntegerField()),
                ('super_user_password', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='SettingsNegativePathModel',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('negative_path_model', models.CharField(max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
                ('settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epsapp.settings')),
            ],
            options={
                'verbose_name_plural': 'Settings Negative Path Model',
            },
        ),
    ]
