# Generated by Django 4.1.6 on 2023-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0031_settings_settingsnegativepathmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdlp',
            name='custom',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
        migrations.AlterField(
            model_name='webdlpdata',
            name='action',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2),
        ),
    ]
