# Generated by Django 4.1.6 on 2023-02-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0033_tokenauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
