# Generated by Django 4.1.6 on 2023-02-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0035_userhardwarerestrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.DateTimeField(null=True)),
                ('logout', models.DateTimeField(null=True)),
                ('hardware_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='epsapp.hardware')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.userauthentication')),
            ],
            options={
                'verbose_name_plural': 'User History',
            },
        ),
    ]
