# Generated by Django 4.1.6 on 2023-02-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0036_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_User_Group_Mapping',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.users')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.usergroup')),
            ],
            options={
                'verbose_name_plural': 'Users User Group Mapping',
            },
        ),
    ]
