# Generated by Django 4.1.6 on 2023-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0038_ipclassification_filecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('old_name', models.CharField(max_length=200)),
                ('new_name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'File Details',
            },
        ),
    ]
