# Generated by Django 4.1.6 on 2023-02-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0039_filedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkDlpData',
        ),
    ]
