# Generated by Django 4.1.6 on 2023-02-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0040_delete_networkdlpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDlpData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2)),
                ('file_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_class_group_nwk', to='epsapp.baseclassificationgroup')),
                ('ip_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_class_group_nwk', to='epsapp.baseclassificationgroup')),
                ('network_dlp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.networkdlp')),
                ('schedule_class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_class_group_nwk', to='epsapp.baseclassificationgroup')),
            ],
            options={
                'verbose_name_plural': 'Network Dlp Data',
            },
        ),
    ]
