# Generated by Django 4.1.6 on 2023-02-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0041_networkdlpdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntivirusNegativePathModel',
        ),
    ]
