# Generated by Django 4.1.6 on 2023-02-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0042_delete_antivirusnegativepathmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntivirusNegativePathModel',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('negative_path_model', models.CharField(max_length=200)),
                ('antivirus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsapp.antivirus')),
            ],
            options={
                'verbose_name_plural': 'Antivirus Negative Path Model',
            },
        ),
    ]
