# Generated by Django 4.1.6 on 2023-02-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0043_antivirusnegativepathmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppClassData',
            new_name='AppClassificationData',
        ),
        migrations.AlterModelOptions(
            name='appclassificationdata',
            options={'verbose_name_plural': 'App Classification Data'},
        ),
    ]
