# Generated by Django 4.1.6 on 2023-02-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0045_webfiltering_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenauth',
            old_name='org_key',
            new_name='organization',
        ),
    ]
