# Generated by Django 4.1.6 on 2023-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0046_rename_org_key_tokenauth_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='country_code',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
