# Generated by Django 4.1.6 on 2023-02-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0049_alter_userauthentication_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthentication',
            old_name='key',
            new_name='id',
        ),
    ]
