# Generated by Django 4.1.6 on 2023-02-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsapp', '0051_rename_key_antivirus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antivirus',
            old_name='id',
            new_name='key',
        ),
    ]
