# Generated by Django 4.1.3 on 2022-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
    ]
