# Generated by Django 4.1.3 on 2022-11-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0002_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Our Clients',
            },
        ),
    ]
