# Generated by Django 4.1.6 on 2023-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0003_ourclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('random', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('random', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ourclients',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image',
        ),
    ]
