# Generated by Django 4.1.6 on 2023-02-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0004_random_randommodel_remove_ourclients_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
