# Generated by Django 4.1.6 on 2023-02-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0006_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')], default=1)),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='joined_at')),
                ('invalid_attempt', models.IntegerField(default=0)),
                ('holding_datetime', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.organization')),
            ],
            options={
                'verbose_name_plural': 'User Authentication',
                'get_latest_by': 'key',
                'unique_together': {('username', 'user_type')},
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.organization')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.role')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.userauthentication')),
            ],
        ),
    ]
