# Generated by Django 4.1.6 on 2023-02-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0007_userauthentication_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
