# Generated by Django 4.1.6 on 2023-02-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0008_delete_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('max_file_size_scan', models.IntegerField()),
                ('extension', models.CharField(max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Antivirus',
                'get_latest_by': 'key',
            },
        ),
    ]
