# Generated by Django 4.1.6 on 2023-02-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0011_antivirusnegativepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurService',
        ),
    ]
