# Generated by Django 4.1.6 on 2023-02-04 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0012_delete_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSuperClass',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Classification Super Class',
                'get_latest_by': 'key',
            },
        ),
        migrations.CreateModel(
            name='AppClassification',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('custom', models.IntegerField(default=1)),
                ('class_super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.classificationsuperclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nividapp.organization')),
            ],
            options={
                'verbose_name_plural': 'App Classification',
                'get_latest_by': 'key',
            },
        ),
    ]
