# Generated by Django 4.1.6 on 2023-02-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0013_classificationsuperclass_appclassification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurClients',
        ),
    ]
