# Generated by Django 4.1.6 on 2023-02-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nividapp', '0015_appcontrolpolicy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='AppControlPolicyData',
        ),
    ]
